services:
  db:
    image: postgres:15-alpine
    container_name: habitflow-postgres
    environment:
      POSTGRES_DB: habitflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: habitflow-redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: habitflow-web
    command: >
      sh -c "
      export DJANGO_SETTINGS_MODULE=config.settings &&
      export PYTHONPATH=/app &&
      echo '=== HabitFlow API ===' &&
      echo 'Waiting for database...' &&
      sleep 5 &&
      echo 'Collecting static files...' &&
      python manage.py collectstatic --noinput &&
      echo 'Applying migrations...' &&
      python manage.py migrate &&
      echo 'Starting Gunicorn...' &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2
      "
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONPATH: /app
      DEBUG: "True"  # временно включите для отладки
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-django-insecure-key}
      POSTGRES_HOST: localhost
      POSTGRES_DB: habitflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres_password}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ALLOWED_HOSTS: localhost,127.0.0.1,web,nginx,158.160.207.244
    expose:
      - "8000"  # Открываем порт только для других контейнеров
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.25-alpine
    container_name: habitflow-nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
